import type { Metadata } from "next"
import Link from "next/link"
import Header from "../components/Header"
import Footer from "../components/Footer"

export const metadata: Metadata = {
  title: "About | Bokamoso Geomatics",
  description: "Learn about Bokamoso Geomatics, its professional land surveying leadership, mission and quality approach.",
}

const principles = [
  { number: "01", title: "Professional practice", body: "A registered Professional Land Surveyor leads the practice and its client work." },
  { number: "02", title: "Quality assurance", body: "Work is independently reviewed before it is submitted to clients." },
  { number: "03", title: "Skills transfer", body: "Knowledge is passed on through workshops, presentations and practical demonstrations." },
]

export default function AboutPage() {
  return (
    <>
      <Header />
      <main>
        <section className="border-b border-border-light bg-surface-light"><div className="max-w-7xl mx-auto px-6 sm:px-8 py-14 sm:py-20"><div className="max-w-4xl"><p className="text-xs font-mono uppercase tracking-widest text-technical-green mb-4">About Bokamoso Geomatics</p><h1 className="font-cabinet-grotesk text-4xl sm:text-5xl lg:text-[56px] leading-[1.1] tracking-tight">Professional geomatics expertise for land, infrastructure and communities.</h1><p className="mt-6 text-base sm:text-lg text-text-muted-dark leading-relaxed max-w-3xl">Bokamoso Geomatics is a Rustenburg-based geomatics and land surveying practice serving municipal, public and private clients.</p></div></div></section>

        <section className="border-b border-border-light bg-background-stone"><div className="max-w-7xl mx-auto px-6 sm:px-8 py-14 sm:py-20 grid lg:grid-cols-12 gap-10 lg:gap-14"><div className="lg:col-span-5"><figure className="border border-border-light bg-surface-light p-3"><img src="/assets/team/surveyor-silhouette.jpg" alt="Survey professional working in the field" className="w-full h-80 sm:h-[480px] object-cover" /><figcaption className="pt-3 text-xs font-mono text-text-muted-dark">Fig. 01 — Field practice</figcaption></figure></div><div className="lg:col-span-7"><p className="text-xs font-mono uppercase tracking-widest text-text-muted-dark">01 — Practice</p><h2 className="mt-3 font-cabinet-grotesk text-3xl sm:text-4xl tracking-tight leading-tight">A considered approach to precise spatial work.</h2><div className="mt-6 space-y-5 text-base text-text-muted-dark leading-relaxed"><p>The practice is led by Kereng Senna, a registered Professional Land Surveyor. Bokamoso Geomatics provides cadastral and engineering surveys, mapping, land management and information, GIS and land reform services.</p><p>We work to provide excellent-quality service to direct clients and broader stakeholders through ethics, honesty, integrity and teamwork.</p></div><div className="mt-8 pt-6 border-t border-border-light grid sm:grid-cols-2 gap-6"><div><p className="text-xs font-mono uppercase tracking-wider text-technical-green mb-2">Vision</p><p className="text-sm leading-relaxed text-text-muted-dark">To be a leading service provider of choice in geomatics across Africa, particularly the SADC region.</p></div><div><p className="text-xs font-mono uppercase tracking-wider text-technical-green mb-2">Mission</p><p className="text-sm leading-relaxed text-text-muted-dark">To deliver excellent-quality service grounded in the highest standards of ethics, honesty, integrity and teamwork.</p></div></div></div></div></section>

        <section className="border-b border-border-light bg-surface-light"><div className="max-w-7xl mx-auto px-6 sm:px-8 py-14 sm:py-20"><div className="grid lg:grid-cols-12 gap-10 lg:gap-14"><div className="lg:col-span-4"><p className="text-xs font-mono uppercase tracking-widest text-text-muted-dark">02 — Leadership</p><h2 className="mt-3 font-cabinet-grotesk text-3xl sm:text-4xl tracking-tight">Professional land surveying experience.</h2></div><div className="lg:col-span-8"><div className="border-t border-border-light"><div className="grid md:grid-cols-[minmax(0,1fr)_12rem] gap-6 py-7 border-b border-border-light"><div><h3 className="font-cabinet-grotesk text-2xl">Kereng Senna</h3><p className="mt-2 text-sm text-text-muted-dark leading-relaxed">Kereng Senna completed a National Diploma in Land Surveying from the Polytechnic of Namibia and a BSc in Land Surveying from the University of KwaZulu-Natal. His career includes work at the Surveyor General’s Office and training in geomatics, town and regional planning, aerial surveying and photogrammetry.</p></div><p className="text-xs font-mono text-technical-green md:text-right">Director · Professional Land Surveyor</p></div><div className="grid sm:grid-cols-3 gap-5 pt-7">{["Cadastral surveying", "Engineering surveys", "GIS & mapping", "Volumetric surveying", "Photogrammetry", "Town planning"].map((item, index) => <div key={item} className="border-t border-border-light pt-3"><span className="text-xs font-mono text-technical-green">{String(index + 1).padStart(2, "0")}</span><p className="mt-5 text-sm font-medium">{item}</p></div>)}</div></div></div></div></div></section>

        <section className="border-b border-border-dark bg-surface-dark text-white"><div className="max-w-7xl mx-auto px-6 sm:px-8 py-14 sm:py-20"><div className="grid lg:grid-cols-12 gap-10 lg:gap-14"><div className="lg:col-span-4"><p className="text-xs font-mono uppercase tracking-widest text-text-muted-light">03 — Quality & development</p><h2 className="mt-3 font-cabinet-grotesk text-3xl sm:text-4xl tracking-tight leading-tight">Quality is built into every project.</h2></div><div className="lg:col-span-8 grid sm:grid-cols-3 border-l border-border-dark">{principles.map((principle) => <article key={principle.number} className="border-r border-t border-b border-border-dark p-6 sm:p-7"><span className="text-xs font-mono text-technical-green">{principle.number}</span><h3 className="mt-12 font-cabinet-grotesk text-xl">{principle.title}</h3><p className="mt-3 text-sm leading-relaxed text-text-muted-light">{principle.body}</p></article>)}</div></div></div></section>

        <section className="bg-surface-light"><div className="max-w-7xl mx-auto px-6 sm:px-8 py-14 sm:py-20"><div className="border border-border-light bg-background-stone p-7 sm:p-10 lg:p-14 flex flex-col lg:flex-row gap-8 lg:items-end lg:justify-between"><div><p className="text-xs font-mono uppercase tracking-widest text-technical-green mb-3">Start a project</p><h2 className="font-cabinet-grotesk text-3xl sm:text-4xl tracking-tight">Need professional survey support?</h2><p className="mt-4 text-base text-text-muted-dark leading-relaxed max-w-2xl">Discuss your site, property or land management project with Bokamoso Geomatics.</p></div><div className="flex flex-wrap gap-3"><Link href="/request-a-quote" className="inline-flex px-5 py-3 bg-surface-dark text-white text-sm font-medium hover:bg-surface-dark-elevated transition-colors">Request a Quote ↗</Link><Link href="/contact" className="inline-flex px-5 py-3 border border-border-light text-text-primary-dark text-sm font-medium hover:border-surface-dark transition-colors">Contact Us</Link></div></div></div></section>
      </main>
      <Footer />
    </>
  )
}
